### ISSUE TITLE
Prusa Mini

### ISSUE THREAD

**Issue by frobert** [zsoltmar/laribo#1]
Hi there, great app! Dos this also works in Prisa Mini? Best regards

**Comment by zsoltmar** [comment]
Hey, for sure.. the only thing to keep in mind is to only use 180x180mm of the available 250x210mm area. You can still just use the MK3 template, just don't go over the 180x180 boundary (zero is left bottom)

**Comment by frobert** [comment]
> Hey, for sure.. the only thing to keep in mind is to only use 180x180mm of the available 250x210mm area. You can still just use the MK3 template, just don't go over the 180x180 boundary (zero is left bottom)

Hi, thanks.. So if I understand correctly, I have to make a smaller SVG with max 180x180mm size and then import it to LARIBO, right?

It would be great if you could add a function/dropdown in your app where user can select the printer type, so users don't brake something on their printers. Also it would be awesome to cover multiple printers as this is quite a great app..

best regards.

**Comment by zsoltmar** [comment]
Since Laribo's bed size is fixed, you'd have to use the same 250x210 size SVG, but only use 180x180 on the bottom left corner of it. I don't have access to a mini, otherwise I might be tempted to add the features. The project is open-source though, so if anyone with the mini and the chops could extend it.
